board_number: 21
output_dir: "./plots"

# Parameters for the calibartion data from the lab
measurement: "CBm12_WS_IRRAD_GRD_11"
calibration_data: "./testboard21_CBm12_WS_IRRAD_GRD_11/ASIC_right/toa_tot_21_2.npz"
# If the board had 2 ASICs, put the file of the right-side one to 'calibration_data', and the left one to 'calibratin_data_left'. (If the board had only 1 ASIC, set calibration_data_left to False.)
calibration_data_left: "./testboard21_CBm12_WS_IRRAD_GRD_11/ASIC_left/toa_tot_21_2.npz"

# Parameters of the histogram data file from the testbeam
histogram_data_dir: "/data/testbeam2/histogram_data/th_scan_sample_21_rc3_6pad_2asic_direct_bonding_irrad/"
histogram_data_files: "histogram_data_run_standalone_th_scan_0.900_2024-07-28_16-21-35.dat"
RC: 3
threshold_per_channel: [0.9,0.9,0.9,0.9,0.9,0.9]
expected_thickness_per_channel: [150,150,150,150,150,150]  # in micrometer
skip_channels: [] # list of channel numbers to skip

# The types of calibration curves to fit onto the calibration data plots. Can be "log", "linear", "spline", or comma separated list (f.e. "log,spline" or ["log","spline"] if you want both on the calib plots)
tested_calibration_types: "log, linear"
# The calibration type to select to prepare the histogram data for the fit. Can be "log" OR "spline" OR "linear", not a list
selected_calibration_type: "log"
calib_bad_point_errorlimit_ns: 3
channels_on_calib_summary_plots: [[0,1,2,3,4,5],[2,3],[4,5]]
summary_plots_xticks_density: 0.2


# An upper cutoff in ns for the raw tot plot
cutoff_ns: 25
# An upper cutoff in fC for the initial Landau fit 
cutoff_fC: 4
# A cutoff in percent (%) for the refined Landau fit: if a point has a larger relative deviation to the initial fit than this value, it is ignored in the refined fit
cutoff_ref: 40
# A lower cutoff to study the effect of near-0 points for the refined fit on the left tail. Separate for each channel, number specifies number of omitted points from the left of the x-axis.
cutoff_lower: [0,0,0,0,0,0]

# Display precision (number of decimals) of MPV on plots:
mpv_display_precision: 3

# initial fit parameters
log_p0: [18,3.5,10] 
landau_p0: [8.0E+6,4.34,1.2]
spline_smoothing_param: 10
